// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUA53MdLv1rvrQ_51f59kyir1oSuMcXlI',
    appId: '1:123580581478:web:d8da7ffd4ad2085d568fa7',
    messagingSenderId: '123580581478',
    projectId: 'product-hunt-20326',
    authDomain: 'product-hunt-20326.firebaseapp.com',
    storageBucket: 'product-hunt-20326.firebasestorage.app',
    measurementId: 'G-MZ89D14RM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwtz9cBiug6LhtRNGbdMDF-wC8jv_MAis',
    appId: '1:123580581478:android:4f250675759c0d06568fa7',
    messagingSenderId: '123580581478',
    projectId: 'product-hunt-20326',
    storageBucket: 'product-hunt-20326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYnsfNyHlM0RNiq3MUEpKvow7Cwti9AgA',
    appId: '1:123580581478:ios:acd313f77eec19b0568fa7',
    messagingSenderId: '123580581478',
    projectId: 'product-hunt-20326',
    storageBucket: 'product-hunt-20326.firebasestorage.app',
    iosBundleId: 'com.example.productHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYnsfNyHlM0RNiq3MUEpKvow7Cwti9AgA',
    appId: '1:123580581478:ios:acd313f77eec19b0568fa7',
    messagingSenderId: '123580581478',
    projectId: 'product-hunt-20326',
    storageBucket: 'product-hunt-20326.firebasestorage.app',
    iosBundleId: 'com.example.productHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUA53MdLv1rvrQ_51f59kyir1oSuMcXlI',
    appId: '1:123580581478:web:26fd24b5076c169a568fa7',
    messagingSenderId: '123580581478',
    projectId: 'product-hunt-20326',
    authDomain: 'product-hunt-20326.firebaseapp.com',
    storageBucket: 'product-hunt-20326.firebasestorage.app',
    measurementId: 'G-LNJZ90CNMH',
  );
}
